// <auto-generated />
namespace SeyahatBlogSitesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DeleteKıtalar_IDColumnInSeyahatlerTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeleteKıtalar_IDColumnInSeyahatlerTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202302191153316_DeleteKıtalar_IDColumnInSeyahatlerTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
